<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class Mkb10DijagnozeSeeder extends Seeder
{
    public function run(): void
    {
        // Dohvati kategorije
        $kategorije = DB::table('mkb10_kategorije')->get()->keyBy('kod_od');

        // Primjeri dijagnoza za svaku kategoriju
        $dijagnoze = [
            // A00-B99 Zarazne i parazitarne bolesti
            ['kategorija' => 'A00', 'kod' => 'A00', 'naziv' => 'Kolera', 'naziv_lat' => 'Cholera'],
            ['kategorija' => 'A00', 'kod' => 'A00.0', 'naziv' => 'Kolera uzrokovana Vibrio cholerae 01, biotip cholerae', 'naziv_lat' => 'Cholera due to Vibrio cholerae 01, biovar cholerae'],
            ['kategorija' => 'A00', 'kod' => 'A00.1', 'naziv' => 'Kolera uzrokovana Vibrio cholerae 01, biotip El Tor', 'naziv_lat' => 'Cholera due to Vibrio cholerae 01, biovar eltor'],
            ['kategorija' => 'A00', 'kod' => 'A00.9', 'naziv' => 'Kolera, neoznačena', 'naziv_lat' => 'Cholera, unspecified'],
            ['kategorija' => 'A00', 'kod' => 'A01', 'naziv' => 'Trbušni tifus i paratifus', 'naziv_lat' => 'Typhoid and paratyphoid fevers'],
            ['kategorija' => 'A00', 'kod' => 'A01.0', 'naziv' => 'Trbušni tifus', 'naziv_lat' => 'Typhoid fever'],
            ['kategorija' => 'A00', 'kod' => 'A02', 'naziv' => 'Druge salmonelozne infekcije', 'naziv_lat' => 'Other salmonella infections'],
            ['kategorija' => 'A00', 'kod' => 'A02.0', 'naziv' => 'Salmonelozni enteritis', 'naziv_lat' => 'Salmonella enteritis'],
            ['kategorija' => 'A00', 'kod' => 'A03', 'naziv' => 'Šigeloza', 'naziv_lat' => 'Shigellosis'],
            ['kategorija' => 'A00', 'kod' => 'A04', 'naziv' => 'Druge bakterijske crijevne infekcije', 'naziv_lat' => 'Other bacterial intestinal infections'],
            ['kategorija' => 'A00', 'kod' => 'A05', 'naziv' => 'Druga bakterijska trovanja hranom', 'naziv_lat' => 'Other bacterial foodborne intoxications'],
            ['kategorija' => 'A00', 'kod' => 'A06', 'naziv' => 'Amebijaza', 'naziv_lat' => 'Amoebiasis'],
            ['kategorija' => 'A00', 'kod' => 'A07', 'naziv' => 'Druge protozoalne crijevne bolesti', 'naziv_lat' => 'Other protozoal intestinal diseases'],
            ['kategorija' => 'A00', 'kod' => 'A08', 'naziv' => 'Virusne i druge označene crijevne infekcije', 'naziv_lat' => 'Viral and other specified intestinal infections'],
            ['kategorija' => 'A00', 'kod' => 'A09', 'naziv' => 'Proljev i gastroenteritis pretpostavljenog infektivnog porijekla', 'naziv_lat' => 'Diarrhoea and gastroenteritis of presumed infectious origin'],
            ['kategorija' => 'A00', 'kod' => 'A15', 'naziv' => 'Tuberkuloza respiratornih organa, bakteriološki i histološki potvrđena', 'naziv_lat' => 'Respiratory tuberculosis, bacteriologically and histologically confirmed'],
            ['kategorija' => 'A00', 'kod' => 'A16', 'naziv' => 'Tuberkuloza respiratornih organa, bakteriološki i histološki nepotvrđena', 'naziv_lat' => 'Respiratory tuberculosis, not confirmed bacteriologically or histologically'],
            ['kategorija' => 'A00', 'kod' => 'B15', 'naziv' => 'Akutni hepatitis A', 'naziv_lat' => 'Acute hepatitis A'],
            ['kategorija' => 'A00', 'kod' => 'B16', 'naziv' => 'Akutni hepatitis B', 'naziv_lat' => 'Acute hepatitis B'],
            ['kategorija' => 'A00', 'kod' => 'B17', 'naziv' => 'Drugi akutni virusni hepatitis', 'naziv_lat' => 'Other acute viral hepatitis'],
            ['kategorija' => 'A00', 'kod' => 'B18', 'naziv' => 'Hronični virusni hepatitis', 'naziv_lat' => 'Chronic viral hepatitis'],
            ['kategorija' => 'A00', 'kod' => 'B20', 'naziv' => 'Bolest uzrokovana HIV-om koja rezultira infektivnim i parazitarnim bolestima', 'naziv_lat' => 'HIV disease resulting in infectious and parasitic diseases'],

            // C00-D48 Novotvorine (tumori)
            ['kategorija' => 'C00', 'kod' => 'C00', 'naziv' => 'Maligna neoplazma usne', 'naziv_lat' => 'Malignant neoplasm of lip'],
            ['kategorija' => 'C00', 'kod' => 'C01', 'naziv' => 'Maligna neoplazma baze jezika', 'naziv_lat' => 'Malignant neoplasm of base of tongue'],
            ['kategorija' => 'C00', 'kod' => 'C02', 'naziv' => 'Maligna neoplazma drugih i neoznačenih dijelova jezika', 'naziv_lat' => 'Malignant neoplasm of other and unspecified parts of tongue'],
            ['kategorija' => 'C00', 'kod' => 'C15', 'naziv' => 'Maligna neoplazma jednjaka', 'naziv_lat' => 'Malignant neoplasm of oesophagus'],
            ['kategorija' => 'C00', 'kod' => 'C16', 'naziv' => 'Maligna neoplazma želuca', 'naziv_lat' => 'Malignant neoplasm of stomach'],
            ['kategorija' => 'C00', 'kod' => 'C18', 'naziv' => 'Maligna neoplazma debelog crijeva', 'naziv_lat' => 'Malignant neoplasm of colon'],
            ['kategorija' => 'C00', 'kod' => 'C20', 'naziv' => 'Maligna neoplazma rektuma', 'naziv_lat' => 'Malignant neoplasm of rectum'],
            ['kategorija' => 'C00', 'kod' => 'C22', 'naziv' => 'Maligna neoplazma jetre i intrahepatičnih žučnih kanala', 'naziv_lat' => 'Malignant neoplasm of liver and intrahepatic bile ducts'],
            ['kategorija' => 'C00', 'kod' => 'C25', 'naziv' => 'Maligna neoplazma gušterače', 'naziv_lat' => 'Malignant neoplasm of pancreas'],
            ['kategorija' => 'C00', 'kod' => 'C34', 'naziv' => 'Maligna neoplazma bronha i pluća', 'naziv_lat' => 'Malignant neoplasm of bronchus and lung'],
            ['kategorija' => 'C00', 'kod' => 'C43', 'naziv' => 'Maligni melanom kože', 'naziv_lat' => 'Malignant melanoma of skin'],
            ['kategorija' => 'C00', 'kod' => 'C50', 'naziv' => 'Maligna neoplazma dojke', 'naziv_lat' => 'Malignant neoplasm of breast'],
            ['kategorija' => 'C00', 'kod' => 'C53', 'naziv' => 'Maligna neoplazma grlića materice', 'naziv_lat' => 'Malignant neoplasm of cervix uteri'],
            ['kategorija' => 'C00', 'kod' => 'C54', 'naziv' => 'Maligna neoplazma tijela materice', 'naziv_lat' => 'Malignant neoplasm of corpus uteri'],
            ['kategorija' => 'C00', 'kod' => 'C56', 'naziv' => 'Maligna neoplazma jajnika', 'naziv_lat' => 'Malignant neoplasm of ovary'],
            ['kategorija' => 'C00', 'kod' => 'C61', 'naziv' => 'Maligna neoplazma prostate', 'naziv_lat' => 'Malignant neoplasm of prostate'],
            ['kategorija' => 'C00', 'kod' => 'C64', 'naziv' => 'Maligna neoplazma bubrega, osim bubrežne karlice', 'naziv_lat' => 'Malignant neoplasm of kidney, except renal pelvis'],
            ['kategorija' => 'C00', 'kod' => 'C67', 'naziv' => 'Maligna neoplazma mokraćnog mjehura', 'naziv_lat' => 'Malignant neoplasm of bladder'],
            ['kategorija' => 'C00', 'kod' => 'C71', 'naziv' => 'Maligna neoplazma mozga', 'naziv_lat' => 'Malignant neoplasm of brain'],
            ['kategorija' => 'C00', 'kod' => 'C73', 'naziv' => 'Maligna neoplazma štitne žlijezde', 'naziv_lat' => 'Malignant neoplasm of thyroid gland'],
            ['kategorija' => 'C00', 'kod' => 'D00', 'naziv' => 'Karcinom in situ usne šupljine, jednjaka i želuca', 'naziv_lat' => 'Carcinoma in situ of oral cavity, oesophagus and stomach'],

            // D50-D89 Bolesti krvi
            ['kategorija' => 'D50', 'kod' => 'D50', 'naziv' => 'Anemija zbog nedostatka željeza', 'naziv_lat' => 'Iron deficiency anaemia'],
            ['kategorija' => 'D50', 'kod' => 'D50.0', 'naziv' => 'Anemija zbog nedostatka željeza sekundarna zbog gubitka krvi (hronična)', 'naziv_lat' => 'Iron deficiency anaemia secondary to blood loss (chronic)'],
            ['kategorija' => 'D50', 'kod' => 'D51', 'naziv' => 'Anemija zbog nedostatka vitamina B12', 'naziv_lat' => 'Vitamin B12 deficiency anaemia'],
            ['kategorija' => 'D50', 'kod' => 'D52', 'naziv' => 'Anemija zbog nedostatka folata', 'naziv_lat' => 'Folate deficiency anaemia'],
            ['kategorija' => 'D50', 'kod' => 'D56', 'naziv' => 'Talasemija', 'naziv_lat' => 'Thalassaemia'],
            ['kategorija' => 'D50', 'kod' => 'D57', 'naziv' => 'Poremećaji srpastih ćelija', 'naziv_lat' => 'Sickle-cell disorders'],
            ['kategorija' => 'D50', 'kod' => 'D64', 'naziv' => 'Druge anemije', 'naziv_lat' => 'Other anaemias'],
            ['kategorija' => 'D50', 'kod' => 'D65', 'naziv' => 'Diseminirana intravaskularna koagulacija', 'naziv_lat' => 'Disseminated intravascular coagulation'],
            ['kategorija' => 'D50', 'kod' => 'D66', 'naziv' => 'Nasljedni nedostatak faktora VIII', 'naziv_lat' => 'Hereditary factor VIII deficiency'],
            ['kategorija' => 'D50', 'kod' => 'D68', 'naziv' => 'Drugi poremećaji koagulacije', 'naziv_lat' => 'Other coagulation defects'],
            ['kategorija' => 'D50', 'kod' => 'D69', 'naziv' => 'Purpura i druga hemoragijska stanja', 'naziv_lat' => 'Purpura and other haemorrhagic conditions'],
            ['kategorija' => 'D50', 'kod' => 'D70', 'naziv' => 'Agranulocitoza', 'naziv_lat' => 'Agranulocytosis'],
            ['kategorija' => 'D50', 'kod' => 'D80', 'naziv' => 'Imunodeficijencija s pretežno defektima antitijela', 'naziv_lat' => 'Immunodeficiency with predominantly antibody defects'],

            // E00-E90 Endokrine bolesti
            ['kategorija' => 'E00', 'kod' => 'E00', 'naziv' => 'Kongenitalni sindrom nedostatka joda', 'naziv_lat' => 'Congenital iodine-deficiency syndrome'],
            ['kategorija' => 'E00', 'kod' => 'E03', 'naziv' => 'Drugi oblici hipotireoze', 'naziv_lat' => 'Other hypothyroidism'],
            ['kategorija' => 'E00', 'kod' => 'E04', 'naziv' => 'Druga netoksična struma', 'naziv_lat' => 'Other nontoxic goitre'],
            ['kategorija' => 'E00', 'kod' => 'E05', 'naziv' => 'Tireotoksikoza (hipertireoza)', 'naziv_lat' => 'Thyrotoxicosis (hyperthyroidism)'],
            ['kategorija' => 'E00', 'kod' => 'E06', 'naziv' => 'Tireoiditis', 'naziv_lat' => 'Thyroiditis'],
            ['kategorija' => 'E00', 'kod' => 'E10', 'naziv' => 'Dijabetes melitus ovisan o inzulinu (tip 1)', 'naziv_lat' => 'Insulin-dependent diabetes mellitus'],
            ['kategorija' => 'E00', 'kod' => 'E10.0', 'naziv' => 'Dijabetes melitus tip 1 s komom', 'naziv_lat' => 'Type 1 diabetes mellitus with coma'],
            ['kategorija' => 'E00', 'kod' => 'E10.1', 'naziv' => 'Dijabetes melitus tip 1 s ketoacidozom', 'naziv_lat' => 'Type 1 diabetes mellitus with ketoacidosis'],
            ['kategorija' => 'E00', 'kod' => 'E11', 'naziv' => 'Dijabetes melitus neovisan o inzulinu (tip 2)', 'naziv_lat' => 'Non-insulin-dependent diabetes mellitus'],
            ['kategorija' => 'E00', 'kod' => 'E11.0', 'naziv' => 'Dijabetes melitus tip 2 s komom', 'naziv_lat' => 'Type 2 diabetes mellitus with coma'],
            ['kategorija' => 'E00', 'kod' => 'E11.2', 'naziv' => 'Dijabetes melitus tip 2 s bubrežnim komplikacijama', 'naziv_lat' => 'Type 2 diabetes mellitus with kidney complications'],
            ['kategorija' => 'E00', 'kod' => 'E11.3', 'naziv' => 'Dijabetes melitus tip 2 s očnim komplikacijama', 'naziv_lat' => 'Type 2 diabetes mellitus with ophthalmic complications'],
            ['kategorija' => 'E00', 'kod' => 'E11.4', 'naziv' => 'Dijabetes melitus tip 2 s neurološkim komplikacijama', 'naziv_lat' => 'Type 2 diabetes mellitus with neurological complications'],
            ['kategorija' => 'E00', 'kod' => 'E14', 'naziv' => 'Neoznačeni dijabetes melitus', 'naziv_lat' => 'Unspecified diabetes mellitus'],
            ['kategorija' => 'E00', 'kod' => 'E66', 'naziv' => 'Pretilost', 'naziv_lat' => 'Obesity'],
            ['kategorija' => 'E00', 'kod' => 'E66.0', 'naziv' => 'Pretilost uzrokovana prekomjernim unosom kalorija', 'naziv_lat' => 'Obesity due to excess calories'],
            ['kategorija' => 'E00', 'kod' => 'E78', 'naziv' => 'Poremećaji metabolizma lipoproteina i druge lipidemije', 'naziv_lat' => 'Disorders of lipoprotein metabolism and other lipidaemias'],
            ['kategorija' => 'E00', 'kod' => 'E78.0', 'naziv' => 'Čista hiperholesterolemija', 'naziv_lat' => 'Pure hypercholesterolaemia'],

            // F00-F99 Mentalni poremećaji
            ['kategorija' => 'F00', 'kod' => 'F00', 'naziv' => 'Demencija kod Alzheimerove bolesti', 'naziv_lat' => 'Dementia in Alzheimer disease'],
            ['kategorija' => 'F00', 'kod' => 'F01', 'naziv' => 'Vaskularna demencija', 'naziv_lat' => 'Vascular dementia'],
            ['kategorija' => 'F00', 'kod' => 'F03', 'naziv' => 'Neoznačena demencija', 'naziv_lat' => 'Unspecified dementia'],
            ['kategorija' => 'F00', 'kod' => 'F10', 'naziv' => 'Mentalni poremećaji i poremećaji ponašanja uzrokovani upotrebom alkohola', 'naziv_lat' => 'Mental and behavioural disorders due to use of alcohol'],
            ['kategorija' => 'F00', 'kod' => 'F11', 'naziv' => 'Mentalni poremećaji uzrokovani upotrebom opioida', 'naziv_lat' => 'Mental and behavioural disorders due to use of opioids'],
            ['kategorija' => 'F00', 'kod' => 'F17', 'naziv' => 'Mentalni poremećaji uzrokovani upotrebom duhana', 'naziv_lat' => 'Mental and behavioural disorders due to use of tobacco'],
            ['kategorija' => 'F00', 'kod' => 'F20', 'naziv' => 'Shizofrenija', 'naziv_lat' => 'Schizophrenia'],
            ['kategorija' => 'F00', 'kod' => 'F31', 'naziv' => 'Bipolarni afektivni poremećaj', 'naziv_lat' => 'Bipolar affective disorder'],
            ['kategorija' => 'F00', 'kod' => 'F32', 'naziv' => 'Depresivna epizoda', 'naziv_lat' => 'Depressive episode'],
            ['kategorija' => 'F00', 'kod' => 'F32.0', 'naziv' => 'Blaga depresivna epizoda', 'naziv_lat' => 'Mild depressive episode'],
            ['kategorija' => 'F00', 'kod' => 'F32.1', 'naziv' => 'Umjerena depresivna epizoda', 'naziv_lat' => 'Moderate depressive episode'],
            ['kategorija' => 'F00', 'kod' => 'F32.2', 'naziv' => 'Teška depresivna epizoda bez psihotičnih simptoma', 'naziv_lat' => 'Severe depressive episode without psychotic symptoms'],
            ['kategorija' => 'F00', 'kod' => 'F33', 'naziv' => 'Rekurentni depresivni poremećaj', 'naziv_lat' => 'Recurrent depressive disorder'],
            ['kategorija' => 'F00', 'kod' => 'F40', 'naziv' => 'Fobični anksiozni poremećaji', 'naziv_lat' => 'Phobic anxiety disorders'],
            ['kategorija' => 'F00', 'kod' => 'F41', 'naziv' => 'Drugi anksiozni poremećaji', 'naziv_lat' => 'Other anxiety disorders'],
            ['kategorija' => 'F00', 'kod' => 'F41.0', 'naziv' => 'Panični poremećaj (epizodna paroksizmalna anksioznost)', 'naziv_lat' => 'Panic disorder (episodic paroxysmal anxiety)'],
            ['kategorija' => 'F00', 'kod' => 'F41.1', 'naziv' => 'Generalizirani anksiozni poremećaj', 'naziv_lat' => 'Generalized anxiety disorder'],
            ['kategorija' => 'F00', 'kod' => 'F43', 'naziv' => 'Reakcija na teški stres i poremećaji prilagođavanja', 'naziv_lat' => 'Reaction to severe stress, and adjustment disorders'],
            ['kategorija' => 'F00', 'kod' => 'F43.1', 'naziv' => 'Posttraumatski stresni poremećaj', 'naziv_lat' => 'Post-traumatic stress disorder'],
            ['kategorija' => 'F00', 'kod' => 'F50', 'naziv' => 'Poremećaji hranjenja', 'naziv_lat' => 'Eating disorders'],
            ['kategorija' => 'F00', 'kod' => 'F50.0', 'naziv' => 'Anoreksija nervoza', 'naziv_lat' => 'Anorexia nervosa'],
            ['kategorija' => 'F00', 'kod' => 'F50.2', 'naziv' => 'Bulimija nervoza', 'naziv_lat' => 'Bulimia nervosa'],
            ['kategorija' => 'F00', 'kod' => 'F51', 'naziv' => 'Neorganski poremećaji spavanja', 'naziv_lat' => 'Nonorganic sleep disorders'],
            ['kategorija' => 'F00', 'kod' => 'F51.0', 'naziv' => 'Neorganska nesanica', 'naziv_lat' => 'Nonorganic insomnia'],

            // G00-G99 Bolesti nervnog sistema
            ['kategorija' => 'G00', 'kod' => 'G00', 'naziv' => 'Bakterijski meningitis, neklasifikovan na drugom mjestu', 'naziv_lat' => 'Bacterial meningitis, not elsewhere classified'],
            ['kategorija' => 'G00', 'kod' => 'G03', 'naziv' => 'Meningitis uzrokovan drugim i neoznačenim uzrocima', 'naziv_lat' => 'Meningitis due to other and unspecified causes'],
            ['kategorija' => 'G00', 'kod' => 'G20', 'naziv' => 'Parkinsonova bolest', 'naziv_lat' => 'Parkinson disease'],
            ['kategorija' => 'G00', 'kod' => 'G25', 'naziv' => 'Drugi ekstrapiramidalni i poremećaji pokreta', 'naziv_lat' => 'Other extrapyramidal and movement disorders'],
            ['kategorija' => 'G00', 'kod' => 'G30', 'naziv' => 'Alzheimerova bolest', 'naziv_lat' => 'Alzheimer disease'],
            ['kategorija' => 'G00', 'kod' => 'G35', 'naziv' => 'Multipla skleroza', 'naziv_lat' => 'Multiple sclerosis'],
            ['kategorija' => 'G00', 'kod' => 'G40', 'naziv' => 'Epilepsija', 'naziv_lat' => 'Epilepsy'],
            ['kategorija' => 'G00', 'kod' => 'G40.0', 'naziv' => 'Lokalizacijski povezana (fokalna) (parcijalna) idiopatska epilepsija', 'naziv_lat' => 'Localization-related (focal) (partial) idiopathic epilepsy'],
            ['kategorija' => 'G00', 'kod' => 'G43', 'naziv' => 'Migrena', 'naziv_lat' => 'Migraine'],
            ['kategorija' => 'G00', 'kod' => 'G43.0', 'naziv' => 'Migrena bez aure', 'naziv_lat' => 'Migraine without aura'],
            ['kategorija' => 'G00', 'kod' => 'G43.1', 'naziv' => 'Migrena s aurom', 'naziv_lat' => 'Migraine with aura'],
            ['kategorija' => 'G00', 'kod' => 'G44', 'naziv' => 'Drugi sindromi glavobolje', 'naziv_lat' => 'Other headache syndromes'],
            ['kategorija' => 'G00', 'kod' => 'G44.2', 'naziv' => 'Tenzijska glavobolja', 'naziv_lat' => 'Tension-type headache'],
            ['kategorija' => 'G00', 'kod' => 'G47', 'naziv' => 'Poremećaji spavanja', 'naziv_lat' => 'Sleep disorders'],
            ['kategorija' => 'G00', 'kod' => 'G47.3', 'naziv' => 'Apneja u snu', 'naziv_lat' => 'Sleep apnoea'],
            ['kategorija' => 'G00', 'kod' => 'G50', 'naziv' => 'Poremećaji trigeminalnog živca', 'naziv_lat' => 'Disorders of trigeminal nerve'],
            ['kategorija' => 'G00', 'kod' => 'G51', 'naziv' => 'Poremećaji facijalnog živca', 'naziv_lat' => 'Facial nerve disorders'],
            ['kategorija' => 'G00', 'kod' => 'G51.0', 'naziv' => 'Bellova paraliza', 'naziv_lat' => 'Bell palsy'],
            ['kategorija' => 'G00', 'kod' => 'G56', 'naziv' => 'Mononeuropatije gornjeg ekstremiteta', 'naziv_lat' => 'Mononeuropathies of upper limb'],
            ['kategorija' => 'G00', 'kod' => 'G56.0', 'naziv' => 'Sindrom karpalnog tunela', 'naziv_lat' => 'Carpal tunnel syndrome'],

            // H00-H59 Bolesti oka
            ['kategorija' => 'H00', 'kod' => 'H00', 'naziv' => 'Hordeolum i halazion', 'naziv_lat' => 'Hordeolum and chalazion'],
            ['kategorija' => 'H00', 'kod' => 'H10', 'naziv' => 'Konjunktivitis', 'naziv_lat' => 'Conjunctivitis'],
            ['kategorija' => 'H00', 'kod' => 'H10.0', 'naziv' => 'Mukopurulentni konjunktivitis', 'naziv_lat' => 'Mucopurulent conjunctivitis'],
            ['kategorija' => 'H00', 'kod' => 'H10.1', 'naziv' => 'Akutni atopijski konjunktivitis', 'naziv_lat' => 'Acute atopic conjunctivitis'],
            ['kategorija' => 'H00', 'kod' => 'H25', 'naziv' => 'Senilna katarakta', 'naziv_lat' => 'Senile cataract'],
            ['kategorija' => 'H00', 'kod' => 'H26', 'naziv' => 'Druge katarakte', 'naziv_lat' => 'Other cataract'],
            ['kategorija' => 'H00', 'kod' => 'H35', 'naziv' => 'Drugi poremećaji mrežnice', 'naziv_lat' => 'Other retinal disorders'],
            ['kategorija' => 'H00', 'kod' => 'H35.3', 'naziv' => 'Degeneracija makule i stražnjeg pola', 'naziv_lat' => 'Degeneration of macula and posterior pole'],
            ['kategorija' => 'H00', 'kod' => 'H40', 'naziv' => 'Glaukom', 'naziv_lat' => 'Glaucoma'],
            ['kategorija' => 'H00', 'kod' => 'H40.1', 'naziv' => 'Primarni glaukom otvorenog ugla', 'naziv_lat' => 'Primary open-angle glaucoma'],
            ['kategorija' => 'H00', 'kod' => 'H52', 'naziv' => 'Poremećaji refrakcije i akomodacije', 'naziv_lat' => 'Disorders of refraction and accommodation'],
            ['kategorija' => 'H00', 'kod' => 'H52.0', 'naziv' => 'Hiperopija (dalekovidnost)', 'naziv_lat' => 'Hypermetropia'],
            ['kategorija' => 'H00', 'kod' => 'H52.1', 'naziv' => 'Miopija (kratkovidnost)', 'naziv_lat' => 'Myopia'],
            ['kategorija' => 'H00', 'kod' => 'H52.2', 'naziv' => 'Astigmatizam', 'naziv_lat' => 'Astigmatism'],
            ['kategorija' => 'H00', 'kod' => 'H52.4', 'naziv' => 'Prezbiopija', 'naziv_lat' => 'Presbyopia'],

            // H60-H95 Bolesti uha
            ['kategorija' => 'H60', 'kod' => 'H60', 'naziv' => 'Otitis externa', 'naziv_lat' => 'Otitis externa'],
            ['kategorija' => 'H60', 'kod' => 'H65', 'naziv' => 'Nesupurativni otitis media', 'naziv_lat' => 'Nonsuppurative otitis media'],
            ['kategorija' => 'H60', 'kod' => 'H66', 'naziv' => 'Supurativni i neoznačeni otitis media', 'naziv_lat' => 'Suppurative and unspecified otitis media'],
            ['kategorija' => 'H60', 'kod' => 'H66.0', 'naziv' => 'Akutni supurativni otitis media', 'naziv_lat' => 'Acute suppurative otitis media'],
            ['kategorija' => 'H60', 'kod' => 'H81', 'naziv' => 'Poremećaji vestibularne funkcije', 'naziv_lat' => 'Disorders of vestibular function'],
            ['kategorija' => 'H60', 'kod' => 'H81.0', 'naziv' => 'Meniereova bolest', 'naziv_lat' => 'Ménière disease'],
            ['kategorija' => 'H60', 'kod' => 'H81.1', 'naziv' => 'Benigni paroksizmalni vertigo', 'naziv_lat' => 'Benign paroxysmal vertigo'],
            ['kategorija' => 'H60', 'kod' => 'H90', 'naziv' => 'Konduktivni i senzorneuralni gubitak sluha', 'naziv_lat' => 'Conductive and sensorineural hearing loss'],
            ['kategorija' => 'H60', 'kod' => 'H91', 'naziv' => 'Drugi gubitak sluha', 'naziv_lat' => 'Other hearing loss'],
            ['kategorija' => 'H60', 'kod' => 'H93', 'naziv' => 'Drugi poremećaji uha, neklasifikovani na drugom mjestu', 'naziv_lat' => 'Other disorders of ear, not elsewhere classified'],
            ['kategorija' => 'H60', 'kod' => 'H93.1', 'naziv' => 'Tinitus', 'naziv_lat' => 'Tinnitus'],

            // I00-I99 Bolesti cirkulacijskog sistema
            ['kategorija' => 'I00', 'kod' => 'I10', 'naziv' => 'Esencijalna (primarna) hipertenzija', 'naziv_lat' => 'Essential (primary) hypertension'],
            ['kategorija' => 'I00', 'kod' => 'I11', 'naziv' => 'Hipertenzivna bolest srca', 'naziv_lat' => 'Hypertensive heart disease'],
            ['kategorija' => 'I00', 'kod' => 'I12', 'naziv' => 'Hipertenzivna bolest bubrega', 'naziv_lat' => 'Hypertensive renal disease'],
            ['kategorija' => 'I00', 'kod' => 'I20', 'naziv' => 'Angina pektoris', 'naziv_lat' => 'Angina pectoris'],
            ['kategorija' => 'I00', 'kod' => 'I20.0', 'naziv' => 'Nestabilna angina', 'naziv_lat' => 'Unstable angina'],
            ['kategorija' => 'I00', 'kod' => 'I21', 'naziv' => 'Akutni infarkt miokarda', 'naziv_lat' => 'Acute myocardial infarction'],
            ['kategorija' => 'I00', 'kod' => 'I21.0', 'naziv' => 'Akutni transmuralni infarkt miokarda prednje stijenke', 'naziv_lat' => 'Acute transmural myocardial infarction of anterior wall'],
            ['kategorija' => 'I00', 'kod' => 'I25', 'naziv' => 'Hronična ishemijska bolest srca', 'naziv_lat' => 'Chronic ischaemic heart disease'],
            ['kategorija' => 'I00', 'kod' => 'I25.1', 'naziv' => 'Aterosklerotska bolest srca', 'naziv_lat' => 'Atherosclerotic heart disease'],
            ['kategorija' => 'I00', 'kod' => 'I26', 'naziv' => 'Plućna embolija', 'naziv_lat' => 'Pulmonary embolism'],
            ['kategorija' => 'I00', 'kod' => 'I42', 'naziv' => 'Kardiomiopatija', 'naziv_lat' => 'Cardiomyopathy'],
            ['kategorija' => 'I00', 'kod' => 'I48', 'naziv' => 'Fibrilacija i undulacija atrija', 'naziv_lat' => 'Atrial fibrillation and flutter'],
            ['kategorija' => 'I00', 'kod' => 'I50', 'naziv' => 'Srčana insuficijencija', 'naziv_lat' => 'Heart failure'],
            ['kategorija' => 'I00', 'kod' => 'I50.0', 'naziv' => 'Kongestivna srčana insuficijencija', 'naziv_lat' => 'Congestive heart failure'],
            ['kategorija' => 'I00', 'kod' => 'I63', 'naziv' => 'Cerebralni infarkt', 'naziv_lat' => 'Cerebral infarction'],
            ['kategorija' => 'I00', 'kod' => 'I64', 'naziv' => 'Moždani udar, neoznačen kao krvarenje ili infarkt', 'naziv_lat' => 'Stroke, not specified as haemorrhage or infarction'],
            ['kategorija' => 'I00', 'kod' => 'I70', 'naziv' => 'Ateroskleroza', 'naziv_lat' => 'Atherosclerosis'],
            ['kategorija' => 'I00', 'kod' => 'I73', 'naziv' => 'Druge periferne vaskularne bolesti', 'naziv_lat' => 'Other peripheral vascular diseases'],
            ['kategorija' => 'I00', 'kod' => 'I80', 'naziv' => 'Flebitis i tromboflebitis', 'naziv_lat' => 'Phlebitis and thrombophlebitis'],
            ['kategorija' => 'I00', 'kod' => 'I83', 'naziv' => 'Varikozne vene donjih ekstremiteta', 'naziv_lat' => 'Varicose veins of lower extremities'],
            ['kategorija' => 'I00', 'kod' => 'I84', 'naziv' => 'Hemoroidi', 'naziv_lat' => 'Haemorrhoids'],

            // J00-J99 Bolesti respiratornog sistema
            ['kategorija' => 'J00', 'kod' => 'J00', 'naziv' => 'Akutni nazofaringitis (prehlada)', 'naziv_lat' => 'Acute nasopharyngitis (common cold)'],
            ['kategorija' => 'J00', 'kod' => 'J01', 'naziv' => 'Akutni sinusitis', 'naziv_lat' => 'Acute sinusitis'],
            ['kategorija' => 'J00', 'kod' => 'J02', 'naziv' => 'Akutni faringitis', 'naziv_lat' => 'Acute pharyngitis'],
            ['kategorija' => 'J00', 'kod' => 'J03', 'naziv' => 'Akutni tonzilitis', 'naziv_lat' => 'Acute tonsillitis'],
            ['kategorija' => 'J00', 'kod' => 'J04', 'naziv' => 'Akutni laringitis i traheitis', 'naziv_lat' => 'Acute laryngitis and tracheitis'],
            ['kategorija' => 'J00', 'kod' => 'J06', 'naziv' => 'Akutne infekcije gornjih respiratornih puteva višestrukih i neoznačenih lokalizacija', 'naziv_lat' => 'Acute upper respiratory infections of multiple and unspecified sites'],
            ['kategorija' => 'J00', 'kod' => 'J06.9', 'naziv' => 'Akutna infekcija gornjih respiratornih puteva, neoznačena', 'naziv_lat' => 'Acute upper respiratory infection, unspecified'],
            ['kategorija' => 'J00', 'kod' => 'J10', 'naziv' => 'Gripa uzrokovana identificiranim virusom gripe', 'naziv_lat' => 'Influenza due to identified influenza virus'],
            ['kategorija' => 'J00', 'kod' => 'J11', 'naziv' => 'Gripa, virus nije identificiran', 'naziv_lat' => 'Influenza, virus not identified'],
            ['kategorija' => 'J00', 'kod' => 'J12', 'naziv' => 'Virusna pneumonija, neklasifikovana na drugom mjestu', 'naziv_lat' => 'Viral pneumonia, not elsewhere classified'],
            ['kategorija' => 'J00', 'kod' => 'J15', 'naziv' => 'Bakterijska pneumonija, neklasifikovana na drugom mjestu', 'naziv_lat' => 'Bacterial pneumonia, not elsewhere classified'],
            ['kategorija' => 'J00', 'kod' => 'J18', 'naziv' => 'Pneumonija, organizam neoznačen', 'naziv_lat' => 'Pneumonia, organism unspecified'],
            ['kategorija' => 'J00', 'kod' => 'J20', 'naziv' => 'Akutni bronhitis', 'naziv_lat' => 'Acute bronchitis'],
            ['kategorija' => 'J00', 'kod' => 'J21', 'naziv' => 'Akutni bronhiolitis', 'naziv_lat' => 'Acute bronchiolitis'],
            ['kategorija' => 'J00', 'kod' => 'J30', 'naziv' => 'Vazomotorni i alergijski rinitis', 'naziv_lat' => 'Vasomotor and allergic rhinitis'],
            ['kategorija' => 'J00', 'kod' => 'J30.1', 'naziv' => 'Alergijski rinitis uzrokovan polenom', 'naziv_lat' => 'Allergic rhinitis due to pollen'],
            ['kategorija' => 'J00', 'kod' => 'J32', 'naziv' => 'Hronični sinusitis', 'naziv_lat' => 'Chronic sinusitis'],
            ['kategorija' => 'J00', 'kod' => 'J35', 'naziv' => 'Hronične bolesti tonzila i adenoida', 'naziv_lat' => 'Chronic diseases of tonsils and adenoids'],
            ['kategorija' => 'J00', 'kod' => 'J40', 'naziv' => 'Bronhitis, neoznačen kao akutni ili hronični', 'naziv_lat' => 'Bronchitis, not specified as acute or chronic'],
            ['kategorija' => 'J00', 'kod' => 'J42', 'naziv' => 'Neoznačeni hronični bronhitis', 'naziv_lat' => 'Unspecified chronic bronchitis'],
            ['kategorija' => 'J00', 'kod' => 'J44', 'naziv' => 'Druga hronična opstruktivna plućna bolest', 'naziv_lat' => 'Other chronic obstructive pulmonary disease'],
            ['kategorija' => 'J00', 'kod' => 'J44.0', 'naziv' => 'KOPB s akutnom infekcijom donjih respiratornih puteva', 'naziv_lat' => 'COPD with acute lower respiratory infection'],
            ['kategorija' => 'J00', 'kod' => 'J44.1', 'naziv' => 'KOPB s akutnom egzacerbacijom, neoznačena', 'naziv_lat' => 'COPD with acute exacerbation, unspecified'],
            ['kategorija' => 'J00', 'kod' => 'J45', 'naziv' => 'Astma', 'naziv_lat' => 'Asthma'],
            ['kategorija' => 'J00', 'kod' => 'J45.0', 'naziv' => 'Pretežno alergijska astma', 'naziv_lat' => 'Predominantly allergic asthma'],
            ['kategorija' => 'J00', 'kod' => 'J45.1', 'naziv' => 'Nealergijska astma', 'naziv_lat' => 'Nonallergic asthma'],

            // K00-K93 Bolesti digestivnog sistema
            ['kategorija' => 'K00', 'kod' => 'K00', 'naziv' => 'Poremećaji razvoja i nicanja zuba', 'naziv_lat' => 'Disorders of tooth development and eruption'],
            ['kategorija' => 'K00', 'kod' => 'K02', 'naziv' => 'Zubni karijes', 'naziv_lat' => 'Dental caries'],
            ['kategorija' => 'K00', 'kod' => 'K04', 'naziv' => 'Bolesti pulpe i periapikalnog tkiva', 'naziv_lat' => 'Diseases of pulp and periapical tissues'],
            ['kategorija' => 'K00', 'kod' => 'K05', 'naziv' => 'Gingivitis i parodontalne bolesti', 'naziv_lat' => 'Gingivitis and periodontal diseases'],
            ['kategorija' => 'K00', 'kod' => 'K20', 'naziv' => 'Ezofagitis', 'naziv_lat' => 'Oesophagitis'],
            ['kategorija' => 'K00', 'kod' => 'K21', 'naziv' => 'Gastroezofagealna refluksna bolest', 'naziv_lat' => 'Gastro-oesophageal reflux disease'],
            ['kategorija' => 'K00', 'kod' => 'K25', 'naziv' => 'Ulkus želuca', 'naziv_lat' => 'Gastric ulcer'],
            ['kategorija' => 'K00', 'kod' => 'K26', 'naziv' => 'Ulkus duodenuma', 'naziv_lat' => 'Duodenal ulcer'],
            ['kategorija' => 'K00', 'kod' => 'K29', 'naziv' => 'Gastritis i duodenitis', 'naziv_lat' => 'Gastritis and duodenitis'],
            ['kategorija' => 'K00', 'kod' => 'K29.7', 'naziv' => 'Gastritis, neoznačen', 'naziv_lat' => 'Gastritis, unspecified'],
            ['kategorija' => 'K00', 'kod' => 'K30', 'naziv' => 'Funkcionalna dispepsija', 'naziv_lat' => 'Functional dyspepsia'],
            ['kategorija' => 'K00', 'kod' => 'K35', 'naziv' => 'Akutni apendicitis', 'naziv_lat' => 'Acute appendicitis'],
            ['kategorija' => 'K00', 'kod' => 'K40', 'naziv' => 'Ingvinalna hernija', 'naziv_lat' => 'Inguinal hernia'],
            ['kategorija' => 'K00', 'kod' => 'K50', 'naziv' => 'Crohnova bolest (regionalni enteritis)', 'naziv_lat' => 'Crohn disease (regional enteritis)'],
            ['kategorija' => 'K00', 'kod' => 'K51', 'naziv' => 'Ulcerozni kolitis', 'naziv_lat' => 'Ulcerative colitis'],
            ['kategorija' => 'K00', 'kod' => 'K58', 'naziv' => 'Sindrom iritabilnog crijeva', 'naziv_lat' => 'Irritable bowel syndrome'],
            ['kategorija' => 'K00', 'kod' => 'K59', 'naziv' => 'Drugi funkcionalni crijevni poremećaji', 'naziv_lat' => 'Other functional intestinal disorders'],
            ['kategorija' => 'K00', 'kod' => 'K59.0', 'naziv' => 'Konstipacija', 'naziv_lat' => 'Constipation'],
            ['kategorija' => 'K00', 'kod' => 'K70', 'naziv' => 'Alkoholna bolest jetre', 'naziv_lat' => 'Alcoholic liver disease'],
            ['kategorija' => 'K00', 'kod' => 'K74', 'naziv' => 'Fibroza i ciroza jetre', 'naziv_lat' => 'Fibrosis and cirrhosis of liver'],
            ['kategorija' => 'K00', 'kod' => 'K76', 'naziv' => 'Druge bolesti jetre', 'naziv_lat' => 'Other diseases of liver'],
            ['kategorija' => 'K00', 'kod' => 'K76.0', 'naziv' => 'Masna jetra, neklasifikovana na drugom mjestu', 'naziv_lat' => 'Fatty (change of) liver, not elsewhere classified'],
            ['kategorija' => 'K00', 'kod' => 'K80', 'naziv' => 'Holelitijaza', 'naziv_lat' => 'Cholelithiasis'],
            ['kategorija' => 'K00', 'kod' => 'K81', 'naziv' => 'Holecistitis', 'naziv_lat' => 'Cholecystitis'],
            ['kategorija' => 'K00', 'kod' => 'K85', 'naziv' => 'Akutni pankreatitis', 'naziv_lat' => 'Acute pancreatitis'],
            ['kategorija' => 'K00', 'kod' => 'K86', 'naziv' => 'Druge bolesti gušterače', 'naziv_lat' => 'Other diseases of pancreas'],

            // L00-L99 Bolesti kože
            ['kategorija' => 'L00', 'kod' => 'L00', 'naziv' => 'Stafilokokni sindrom opečene kože', 'naziv_lat' => 'Staphylococcal scalded skin syndrome'],
            ['kategorija' => 'L00', 'kod' => 'L01', 'naziv' => 'Impetigo', 'naziv_lat' => 'Impetigo'],
            ['kategorija' => 'L00', 'kod' => 'L02', 'naziv' => 'Kožni apsces, furunkul i karbunkul', 'naziv_lat' => 'Cutaneous abscess, furuncle and carbuncle'],
            ['kategorija' => 'L00', 'kod' => 'L03', 'naziv' => 'Celulitis', 'naziv_lat' => 'Cellulitis'],
            ['kategorija' => 'L00', 'kod' => 'L20', 'naziv' => 'Atopijski dermatitis', 'naziv_lat' => 'Atopic dermatitis'],
            ['kategorija' => 'L00', 'kod' => 'L21', 'naziv' => 'Seboroični dermatitis', 'naziv_lat' => 'Seborrhoeic dermatitis'],
            ['kategorija' => 'L00', 'kod' => 'L23', 'naziv' => 'Alergijski kontaktni dermatitis', 'naziv_lat' => 'Allergic contact dermatitis'],
            ['kategorija' => 'L00', 'kod' => 'L30', 'naziv' => 'Drugi dermatitis', 'naziv_lat' => 'Other dermatitis'],
            ['kategorija' => 'L00', 'kod' => 'L40', 'naziv' => 'Psorijaza', 'naziv_lat' => 'Psoriasis'],
            ['kategorija' => 'L00', 'kod' => 'L40.0', 'naziv' => 'Psorijaza vulgaris', 'naziv_lat' => 'Psoriasis vulgaris'],
            ['kategorija' => 'L00', 'kod' => 'L50', 'naziv' => 'Urtikarija', 'naziv_lat' => 'Urticaria'],
            ['kategorija' => 'L00', 'kod' => 'L60', 'naziv' => 'Poremećaji noktiju', 'naziv_lat' => 'Nail disorders'],
            ['kategorija' => 'L00', 'kod' => 'L63', 'naziv' => 'Alopecija areata', 'naziv_lat' => 'Alopecia areata'],
            ['kategorija' => 'L00', 'kod' => 'L70', 'naziv' => 'Akne', 'naziv_lat' => 'Acne'],
            ['kategorija' => 'L00', 'kod' => 'L70.0', 'naziv' => 'Akne vulgaris', 'naziv_lat' => 'Acne vulgaris'],
            ['kategorija' => 'L00', 'kod' => 'L80', 'naziv' => 'Vitiligo', 'naziv_lat' => 'Vitiligo'],
            ['kategorija' => 'L00', 'kod' => 'L82', 'naziv' => 'Seboroična keratoza', 'naziv_lat' => 'Seborrhoeic keratosis'],

            // M00-M99 Bolesti mišićno-koštanog sistema
            ['kategorija' => 'M00', 'kod' => 'M05', 'naziv' => 'Seropozitivni reumatoidni artritis', 'naziv_lat' => 'Seropositive rheumatoid arthritis'],
            ['kategorija' => 'M00', 'kod' => 'M06', 'naziv' => 'Drugi reumatoidni artritis', 'naziv_lat' => 'Other rheumatoid arthritis'],
            ['kategorija' => 'M00', 'kod' => 'M10', 'naziv' => 'Giht', 'naziv_lat' => 'Gout'],
            ['kategorija' => 'M00', 'kod' => 'M15', 'naziv' => 'Poliartroza', 'naziv_lat' => 'Polyarthrosis'],
            ['kategorija' => 'M00', 'kod' => 'M16', 'naziv' => 'Koksartroza (artroza kuka)', 'naziv_lat' => 'Coxarthrosis (arthrosis of hip)'],
            ['kategorija' => 'M00', 'kod' => 'M17', 'naziv' => 'Gonartroza (artroza koljena)', 'naziv_lat' => 'Gonarthrosis (arthrosis of knee)'],
            ['kategorija' => 'M00', 'kod' => 'M19', 'naziv' => 'Druge artroze', 'naziv_lat' => 'Other arthrosis'],
            ['kategorija' => 'M00', 'kod' => 'M23', 'naziv' => 'Unutrašnji poremećaj koljena', 'naziv_lat' => 'Internal derangement of knee'],
            ['kategorija' => 'M00', 'kod' => 'M25', 'naziv' => 'Drugi poremećaji zglobova, neklasifikovani na drugom mjestu', 'naziv_lat' => 'Other joint disorders, not elsewhere classified'],
            ['kategorija' => 'M00', 'kod' => 'M32', 'naziv' => 'Sistemski eritematozni lupus', 'naziv_lat' => 'Systemic lupus erythematosus'],
            ['kategorija' => 'M00', 'kod' => 'M35', 'naziv' => 'Drugi sistemski poremećaji vezivnog tkiva', 'naziv_lat' => 'Other systemic involvement of connective tissue'],
            ['kategorija' => 'M00', 'kod' => 'M41', 'naziv' => 'Skolioza', 'naziv_lat' => 'Scoliosis'],
            ['kategorija' => 'M00', 'kod' => 'M42', 'naziv' => 'Osteohondroza kičme', 'naziv_lat' => 'Spinal osteochondrosis'],
            ['kategorija' => 'M00', 'kod' => 'M43', 'naziv' => 'Druge deformirajuće dorzopatije', 'naziv_lat' => 'Other deforming dorsopathies'],
            ['kategorija' => 'M00', 'kod' => 'M47', 'naziv' => 'Spondiloza', 'naziv_lat' => 'Spondylosis'],
            ['kategorija' => 'M00', 'kod' => 'M50', 'naziv' => 'Poremećaji cervikalnog intervertebralnog diska', 'naziv_lat' => 'Cervical disc disorders'],
            ['kategorija' => 'M00', 'kod' => 'M51', 'naziv' => 'Drugi poremećaji intervertebralnog diska', 'naziv_lat' => 'Other intervertebral disc disorders'],
            ['kategorija' => 'M00', 'kod' => 'M51.1', 'naziv' => 'Lumbalni i drugi poremećaji intervertebralnog diska s radikulopatijom', 'naziv_lat' => 'Lumbar and other intervertebral disc disorders with radiculopathy'],
            ['kategorija' => 'M00', 'kod' => 'M54', 'naziv' => 'Dorsalgija', 'naziv_lat' => 'Dorsalgia'],
            ['kategorija' => 'M00', 'kod' => 'M54.4', 'naziv' => 'Lumbago s išijasom', 'naziv_lat' => 'Lumbago with sciatica'],
            ['kategorija' => 'M00', 'kod' => 'M54.5', 'naziv' => 'Bol u donjem dijelu leđa', 'naziv_lat' => 'Low back pain'],
            ['kategorija' => 'M00', 'kod' => 'M62', 'naziv' => 'Drugi poremećaji mišića', 'naziv_lat' => 'Other disorders of muscle'],
            ['kategorija' => 'M00', 'kod' => 'M75', 'naziv' => 'Lezije ramena', 'naziv_lat' => 'Shoulder lesions'],
            ['kategorija' => 'M00', 'kod' => 'M75.1', 'naziv' => 'Sindrom rotatorne manžete', 'naziv_lat' => 'Rotator cuff syndrome'],
            ['kategorija' => 'M00', 'kod' => 'M77', 'naziv' => 'Druge entezopatije', 'naziv_lat' => 'Other enthesopathies'],
            ['kategorija' => 'M00', 'kod' => 'M77.0', 'naziv' => 'Medijalni epikondilitis', 'naziv_lat' => 'Medial epicondylitis'],
            ['kategorija' => 'M00', 'kod' => 'M77.1', 'naziv' => 'Lateralni epikondilitis (teniski lakat)', 'naziv_lat' => 'Lateral epicondylitis'],
            ['kategorija' => 'M00', 'kod' => 'M79', 'naziv' => 'Drugi poremećaji mekog tkiva, neklasifikovani na drugom mjestu', 'naziv_lat' => 'Other soft tissue disorders, not elsewhere classified'],
            ['kategorija' => 'M00', 'kod' => 'M79.1', 'naziv' => 'Mijalgija', 'naziv_lat' => 'Myalgia'],
            ['kategorija' => 'M00', 'kod' => 'M79.3', 'naziv' => 'Panikulitis, neoznačen', 'naziv_lat' => 'Panniculitis, unspecified'],
            ['kategorija' => 'M00', 'kod' => 'M80', 'naziv' => 'Osteoporoza s patološkim prijelomom', 'naziv_lat' => 'Osteoporosis with pathological fracture'],
            ['kategorija' => 'M00', 'kod' => 'M81', 'naziv' => 'Osteoporoza bez patološkog prijeloma', 'naziv_lat' => 'Osteoporosis without pathological fracture'],

            // N00-N99 Bolesti genitourinarnog sistema
            ['kategorija' => 'N00', 'kod' => 'N00', 'naziv' => 'Akutni nefritički sindrom', 'naziv_lat' => 'Acute nephritic syndrome'],
            ['kategorija' => 'N00', 'kod' => 'N03', 'naziv' => 'Hronični nefritički sindrom', 'naziv_lat' => 'Chronic nephritic syndrome'],
            ['kategorija' => 'N00', 'kod' => 'N04', 'naziv' => 'Nefrotski sindrom', 'naziv_lat' => 'Nephrotic syndrome'],
            ['kategorija' => 'N00', 'kod' => 'N10', 'naziv' => 'Akutni tubulointersticijski nefritis', 'naziv_lat' => 'Acute tubulo-interstitial nephritis'],
            ['kategorija' => 'N00', 'kod' => 'N17', 'naziv' => 'Akutna bubrežna insuficijencija', 'naziv_lat' => 'Acute renal failure'],
            ['kategorija' => 'N00', 'kod' => 'N18', 'naziv' => 'Hronična bubrežna bolest', 'naziv_lat' => 'Chronic kidney disease'],
            ['kategorija' => 'N00', 'kod' => 'N18.3', 'naziv' => 'Hronična bubrežna bolest, stadij 3', 'naziv_lat' => 'Chronic kidney disease, stage 3'],
            ['kategorija' => 'N00', 'kod' => 'N18.5', 'naziv' => 'Hronična bubrežna bolest, stadij 5', 'naziv_lat' => 'Chronic kidney disease, stage 5'],
            ['kategorija' => 'N00', 'kod' => 'N20', 'naziv' => 'Kamen bubrega i uretera', 'naziv_lat' => 'Calculus of kidney and ureter'],
            ['kategorija' => 'N00', 'kod' => 'N30', 'naziv' => 'Cistitis', 'naziv_lat' => 'Cystitis'],
            ['kategorija' => 'N00', 'kod' => 'N30.0', 'naziv' => 'Akutni cistitis', 'naziv_lat' => 'Acute cystitis'],
            ['kategorija' => 'N00', 'kod' => 'N39', 'naziv' => 'Drugi poremećaji urinarnog sistema', 'naziv_lat' => 'Other disorders of urinary system'],
            ['kategorija' => 'N00', 'kod' => 'N39.0', 'naziv' => 'Infekcija urinarnog trakta, lokalizacija neoznačena', 'naziv_lat' => 'Urinary tract infection, site not specified'],
            ['kategorija' => 'N00', 'kod' => 'N40', 'naziv' => 'Hiperplazija prostate', 'naziv_lat' => 'Hyperplasia of prostate'],
            ['kategorija' => 'N00', 'kod' => 'N41', 'naziv' => 'Upalne bolesti prostate', 'naziv_lat' => 'Inflammatory diseases of prostate'],
            ['kategorija' => 'N00', 'kod' => 'N60', 'naziv' => 'Benigna displazija dojke', 'naziv_lat' => 'Benign mammary dysplasia'],
            ['kategorija' => 'N00', 'kod' => 'N63', 'naziv' => 'Neoznačena kvržica u dojci', 'naziv_lat' => 'Unspecified lump in breast'],
            ['kategorija' => 'N00', 'kod' => 'N70', 'naziv' => 'Salpingitis i ooforitis', 'naziv_lat' => 'Salpingitis and oophoritis'],
            ['kategorija' => 'N00', 'kod' => 'N76', 'naziv' => 'Druge upale vagine i vulve', 'naziv_lat' => 'Other inflammation of vagina and vulva'],
            ['kategorija' => 'N00', 'kod' => 'N80', 'naziv' => 'Endometrioza', 'naziv_lat' => 'Endometriosis'],
            ['kategorija' => 'N00', 'kod' => 'N83', 'naziv' => 'Neupalni poremećaji jajnika, jajovoda i širokog ligamenta', 'naziv_lat' => 'Noninflammatory disorders of ovary, fallopian tube and broad ligament'],
            ['kategorija' => 'N00', 'kod' => 'N85', 'naziv' => 'Drugi neupalni poremećaji materice, osim grlića', 'naziv_lat' => 'Other noninflammatory disorders of uterus, except cervix'],
            ['kategorija' => 'N00', 'kod' => 'N92', 'naziv' => 'Preobilna, česta i neredovna menstruacija', 'naziv_lat' => 'Excessive, frequent and irregular menstruation'],
            ['kategorija' => 'N00', 'kod' => 'N94', 'naziv' => 'Bol i druga stanja povezana sa ženskim genitalnim organima i menstrualnim ciklusom', 'naziv_lat' => 'Pain and other conditions associated with female genital organs and menstrual cycle'],
            ['kategorija' => 'N00', 'kod' => 'N95', 'naziv' => 'Menopauzalni i drugi perimenopaualni poremećaji', 'naziv_lat' => 'Menopausal and other perimenopausal disorders'],

            // O00-O99 Trudnoća, porođaj i babinje
            ['kategorija' => 'O00', 'kod' => 'O00', 'naziv' => 'Ektopična trudnoća', 'naziv_lat' => 'Ectopic pregnancy'],
            ['kategorija' => 'O00', 'kod' => 'O03', 'naziv' => 'Spontani pobačaj', 'naziv_lat' => 'Spontaneous abortion'],
            ['kategorija' => 'O00', 'kod' => 'O10', 'naziv' => 'Prethodno postojeća hipertenzija koja komplicira trudnoću, porođaj i babinje', 'naziv_lat' => 'Pre-existing hypertension complicating pregnancy, childbirth and the puerperium'],
            ['kategorija' => 'O00', 'kod' => 'O14', 'naziv' => 'Gestacijska hipertenzija s značajnom proteinurijom', 'naziv_lat' => 'Gestational hypertension with significant proteinuria'],
            ['kategorija' => 'O00', 'kod' => 'O21', 'naziv' => 'Prekomjerno povraćanje u trudnoći', 'naziv_lat' => 'Excessive vomiting in pregnancy'],
            ['kategorija' => 'O00', 'kod' => 'O24', 'naziv' => 'Dijabetes melitus u trudnoći', 'naziv_lat' => 'Diabetes mellitus in pregnancy'],
            ['kategorija' => 'O00', 'kod' => 'O36', 'naziv' => 'Majčina njega zbog drugih poznatih ili suspektnih problema fetusa', 'naziv_lat' => 'Maternal care for other known or suspected fetal problems'],
            ['kategorija' => 'O00', 'kod' => 'O42', 'naziv' => 'Prijevremena ruptura membrana', 'naziv_lat' => 'Premature rupture of membranes'],
            ['kategorija' => 'O00', 'kod' => 'O60', 'naziv' => 'Prijevremeni porođaj', 'naziv_lat' => 'Preterm labour'],
            ['kategorija' => 'O00', 'kod' => 'O80', 'naziv' => 'Spontani porođaj jednog djeteta', 'naziv_lat' => 'Single spontaneous delivery'],
            ['kategorija' => 'O00', 'kod' => 'O82', 'naziv' => 'Porođaj carskim rezom', 'naziv_lat' => 'Delivery by caesarean section'],

            // P00-P96 Perinatalna stanja
            ['kategorija' => 'P00', 'kod' => 'P05', 'naziv' => 'Usporen rast i pothranjenost fetusa', 'naziv_lat' => 'Slow fetal growth and fetal malnutrition'],
            ['kategorija' => 'P00', 'kod' => 'P07', 'naziv' => 'Poremećaji povezani s kratkim trajanjem trudnoće i malom porođajnom težinom', 'naziv_lat' => 'Disorders related to short gestation and low birth weight'],
            ['kategorija' => 'P00', 'kod' => 'P22', 'naziv' => 'Respiratorni distres novorođenčeta', 'naziv_lat' => 'Respiratory distress of newborn'],
            ['kategorija' => 'P00', 'kod' => 'P36', 'naziv' => 'Bakterijska sepsa novorođenčeta', 'naziv_lat' => 'Bacterial sepsis of newborn'],
            ['kategorija' => 'P00', 'kod' => 'P59', 'naziv' => 'Neonatalna žutica zbog drugih i neoznačenih uzroka', 'naziv_lat' => 'Neonatal jaundice from other and unspecified causes'],

            // Q00-Q99 Urođene malformacije
            ['kategorija' => 'Q00', 'kod' => 'Q00', 'naziv' => 'Anencefalija i slične malformacije', 'naziv_lat' => 'Anencephaly and similar malformations'],
            ['kategorija' => 'Q00', 'kod' => 'Q03', 'naziv' => 'Kongenitalni hidrocefalus', 'naziv_lat' => 'Congenital hydrocephalus'],
            ['kategorija' => 'Q00', 'kod' => 'Q05', 'naziv' => 'Spina bifida', 'naziv_lat' => 'Spina bifida'],
            ['kategorija' => 'Q00', 'kod' => 'Q20', 'naziv' => 'Kongenitalne malformacije srčanih komora i veza', 'naziv_lat' => 'Congenital malformations of cardiac chambers and connections'],
            ['kategorija' => 'Q00', 'kod' => 'Q21', 'naziv' => 'Kongenitalne malformacije srčanih pregrada', 'naziv_lat' => 'Congenital malformations of cardiac septa'],
            ['kategorija' => 'Q00', 'kod' => 'Q35', 'naziv' => 'Rascjep nepca', 'naziv_lat' => 'Cleft palate'],
            ['kategorija' => 'Q00', 'kod' => 'Q36', 'naziv' => 'Rascjep usne', 'naziv_lat' => 'Cleft lip'],
            ['kategorija' => 'Q00', 'kod' => 'Q65', 'naziv' => 'Kongenitalne deformacije kuka', 'naziv_lat' => 'Congenital deformities of hip'],
            ['kategorija' => 'Q00', 'kod' => 'Q66', 'naziv' => 'Kongenitalne deformacije stopala', 'naziv_lat' => 'Congenital deformities of feet'],
            ['kategorija' => 'Q00', 'kod' => 'Q90', 'naziv' => 'Downov sindrom', 'naziv_lat' => 'Down syndrome'],

            // R00-R99 Simptomi i znakovi
            ['kategorija' => 'R00', 'kod' => 'R00', 'naziv' => 'Abnormalnosti otkucaja srca', 'naziv_lat' => 'Abnormalities of heart beat'],
            ['kategorija' => 'R00', 'kod' => 'R05', 'naziv' => 'Kašalj', 'naziv_lat' => 'Cough'],
            ['kategorija' => 'R00', 'kod' => 'R06', 'naziv' => 'Abnormalnosti disanja', 'naziv_lat' => 'Abnormalities of breathing'],
            ['kategorija' => 'R00', 'kod' => 'R07', 'naziv' => 'Bol u grlu i prsima', 'naziv_lat' => 'Pain in throat and chest'],
            ['kategorija' => 'R00', 'kod' => 'R10', 'naziv' => 'Bol u abdomenu i karlici', 'naziv_lat' => 'Abdominal and pelvic pain'],
            ['kategorija' => 'R00', 'kod' => 'R11', 'naziv' => 'Mučnina i povraćanje', 'naziv_lat' => 'Nausea and vomiting'],
            ['kategorija' => 'R00', 'kod' => 'R21', 'naziv' => 'Osip i druge nespecifične kožne erupcije', 'naziv_lat' => 'Rash and other nonspecific skin eruption'],
            ['kategorija' => 'R00', 'kod' => 'R42', 'naziv' => 'Vrtoglavica i ošamućenost', 'naziv_lat' => 'Dizziness and giddiness'],
            ['kategorija' => 'R00', 'kod' => 'R50', 'naziv' => 'Povišena tjelesna temperatura nepoznatog porijekla', 'naziv_lat' => 'Fever of unknown origin'],
            ['kategorija' => 'R00', 'kod' => 'R51', 'naziv' => 'Glavobolja', 'naziv_lat' => 'Headache'],
            ['kategorija' => 'R00', 'kod' => 'R52', 'naziv' => 'Bol, neklasifikovana na drugom mjestu', 'naziv_lat' => 'Pain, not elsewhere classified'],
            ['kategorija' => 'R00', 'kod' => 'R53', 'naziv' => 'Malaksalost i umor', 'naziv_lat' => 'Malaise and fatigue'],
            ['kategorija' => 'R00', 'kod' => 'R55', 'naziv' => 'Sinkopa i kolaps', 'naziv_lat' => 'Syncope and collapse'],
            ['kategorija' => 'R00', 'kod' => 'R63', 'naziv' => 'Simptomi i znakovi koji se odnose na unos hrane i tekućine', 'naziv_lat' => 'Symptoms and signs concerning food and fluid intake'],

            // S00-T98 Povrede i trovanja
            ['kategorija' => 'S00', 'kod' => 'S00', 'naziv' => 'Površinska povreda glave', 'naziv_lat' => 'Superficial injury of head'],
            ['kategorija' => 'S00', 'kod' => 'S02', 'naziv' => 'Prijelom kostiju lubanje i lica', 'naziv_lat' => 'Fracture of skull and facial bones'],
            ['kategorija' => 'S00', 'kod' => 'S06', 'naziv' => 'Intrakranijalna povreda', 'naziv_lat' => 'Intracranial injury'],
            ['kategorija' => 'S00', 'kod' => 'S06.0', 'naziv' => 'Potres mozga', 'naziv_lat' => 'Concussion'],
            ['kategorija' => 'S00', 'kod' => 'S22', 'naziv' => 'Prijelom rebra, prsne kosti i torakalne kičme', 'naziv_lat' => 'Fracture of rib(s), sternum and thoracic spine'],
            ['kategorija' => 'S00', 'kod' => 'S32', 'naziv' => 'Prijelom lumbalne kičme i karlice', 'naziv_lat' => 'Fracture of lumbar spine and pelvis'],
            ['kategorija' => 'S00', 'kod' => 'S42', 'naziv' => 'Prijelom ramena i nadlaktice', 'naziv_lat' => 'Fracture of shoulder and upper arm'],
            ['kategorija' => 'S00', 'kod' => 'S52', 'naziv' => 'Prijelom podlaktice', 'naziv_lat' => 'Fracture of forearm'],
            ['kategorija' => 'S00', 'kod' => 'S62', 'naziv' => 'Prijelom ručnog zgloba i šake', 'naziv_lat' => 'Fracture at wrist and hand level'],
            ['kategorija' => 'S00', 'kod' => 'S72', 'naziv' => 'Prijelom femura', 'naziv_lat' => 'Fracture of femur'],
            ['kategorija' => 'S00', 'kod' => 'S82', 'naziv' => 'Prijelom potkoljenice, uključujući skočni zglob', 'naziv_lat' => 'Fracture of lower leg, including ankle'],
            ['kategorija' => 'S00', 'kod' => 'S83', 'naziv' => 'Iščašenje, uganuće i istegnuće zglobova i ligamenata koljena', 'naziv_lat' => 'Dislocation, sprain and strain of joints and ligaments of knee'],
            ['kategorija' => 'S00', 'kod' => 'S93', 'naziv' => 'Iščašenje, uganuće i istegnuće zglobova i ligamenata skočnog zgloba i stopala', 'naziv_lat' => 'Dislocation, sprain and strain of joints and ligaments at ankle and foot level'],
            ['kategorija' => 'S00', 'kod' => 'T14', 'naziv' => 'Povreda neoznačene regije tijela', 'naziv_lat' => 'Injury of unspecified body region'],
            ['kategorija' => 'S00', 'kod' => 'T78', 'naziv' => 'Štetni efekti, neklasifikovani na drugom mjestu', 'naziv_lat' => 'Adverse effects, not elsewhere classified'],
            ['kategorija' => 'S00', 'kod' => 'T78.4', 'naziv' => 'Alergija, neoznačena', 'naziv_lat' => 'Allergy, unspecified'],

            // U00-U89 Šifre za posebne namjene
            ['kategorija' => 'U00', 'kod' => 'U07', 'naziv' => 'Hitne šifre za nove bolesti', 'naziv_lat' => 'Emergency use codes for new diseases'],
            ['kategorija' => 'U00', 'kod' => 'U07.1', 'naziv' => 'COVID-19, virus identificiran', 'naziv_lat' => 'COVID-19, virus identified'],
            ['kategorija' => 'U00', 'kod' => 'U07.2', 'naziv' => 'COVID-19, virus nije identificiran', 'naziv_lat' => 'COVID-19, virus not identified'],
            ['kategorija' => 'U00', 'kod' => 'U09', 'naziv' => 'Stanje nakon COVID-19', 'naziv_lat' => 'Post COVID-19 condition'],
            ['kategorija' => 'U00', 'kod' => 'U09.9', 'naziv' => 'Stanje nakon COVID-19, neoznačeno', 'naziv_lat' => 'Post COVID-19 condition, unspecified'],

            // V01-Y98 Spoljašnji uzroci
            ['kategorija' => 'V01', 'kod' => 'V01', 'naziv' => 'Pješak povrijeđen u sudaru s biciklom', 'naziv_lat' => 'Pedestrian injured in collision with pedal cycle'],
            ['kategorija' => 'V01', 'kod' => 'W01', 'naziv' => 'Pad na istoj razini od klizanja, spoticanja i posrtanja', 'naziv_lat' => 'Fall on same level from slipping, tripping and stumbling'],
            ['kategorija' => 'V01', 'kod' => 'W10', 'naziv' => 'Pad na i sa stepenica i stepeništa', 'naziv_lat' => 'Fall on and from stairs and steps'],
            ['kategorija' => 'V01', 'kod' => 'W19', 'naziv' => 'Neoznačeni pad', 'naziv_lat' => 'Unspecified fall'],
            ['kategorija' => 'V01', 'kod' => 'X58', 'naziv' => 'Izlaganje drugim označenim faktorima', 'naziv_lat' => 'Exposure to other specified factors'],
            ['kategorija' => 'V01', 'kod' => 'Y83', 'naziv' => 'Hirurška operacija i drugi hirurški postupci kao uzrok abnormalne reakcije pacijenta', 'naziv_lat' => 'Surgical operation and other surgical procedures as the cause of abnormal reaction of the patient'],

            // Z00-Z99 Faktori koji utiču na zdravstveno stanje
            ['kategorija' => 'Z00', 'kod' => 'Z00', 'naziv' => 'Opći pregled i ispitivanje osoba bez tegoba ili prijavljene dijagnoze', 'naziv_lat' => 'General examination and investigation of persons without complaint or reported diagnosis'],
            ['kategorija' => 'Z00', 'kod' => 'Z00.0', 'naziv' => 'Opći medicinski pregled', 'naziv_lat' => 'General medical examination'],
            ['kategorija' => 'Z00', 'kod' => 'Z01', 'naziv' => 'Drugi specijalni pregledi i ispitivanja osoba bez tegoba ili prijavljene dijagnoze', 'naziv_lat' => 'Other special examinations and investigations of persons without complaint or reported diagnosis'],
            ['kategorija' => 'Z00', 'kod' => 'Z12', 'naziv' => 'Specijalni skrining pregled za neoplazme', 'naziv_lat' => 'Special screening examination for neoplasms'],
            ['kategorija' => 'Z00', 'kod' => 'Z23', 'naziv' => 'Potreba za imunizacijom protiv pojedinačnih bakterijskih bolesti', 'naziv_lat' => 'Need for immunization against single bacterial diseases'],
            ['kategorija' => 'Z00', 'kod' => 'Z30', 'naziv' => 'Kontracepcijsko savjetovanje i upravljanje', 'naziv_lat' => 'Contraceptive counselling and management'],
            ['kategorija' => 'Z00', 'kod' => 'Z34', 'naziv' => 'Nadzor normalne trudnoće', 'naziv_lat' => 'Supervision of normal pregnancy'],
            ['kategorija' => 'Z00', 'kod' => 'Z71', 'naziv' => 'Osobe koje se obraćaju zdravstvenoj službi radi drugog savjetovanja i medicinskog savjeta', 'naziv_lat' => 'Persons encountering health services for other counselling and medical advice'],
            ['kategorija' => 'Z00', 'kod' => 'Z72', 'naziv' => 'Problemi povezani sa stilom života', 'naziv_lat' => 'Problems related to lifestyle'],
            ['kategorija' => 'Z00', 'kod' => 'Z72.0', 'naziv' => 'Upotreba duhana', 'naziv_lat' => 'Tobacco use'],
            ['kategorija' => 'Z00', 'kod' => 'Z76', 'naziv' => 'Osobe koje se obraćaju zdravstvenoj službi u drugim okolnostima', 'naziv_lat' => 'Persons encountering health services in other circumstances'],
            ['kategorija' => 'Z00', 'kod' => 'Z96', 'naziv' => 'Prisustvo drugih funkcionalnih implantata', 'naziv_lat' => 'Presence of other functional implants'],
        ];

        foreach ($dijagnoze as $dijagnoza) {
            $kategorija = $kategorije->get($dijagnoza['kategorija']);
            if (!$kategorija) {
                continue;
            }

            DB::table('mkb10_dijagnoze')->updateOrInsert(
                ['kod' => $dijagnoza['kod']],
                [
                    'kategorija_id' => $kategorija->id,
                    'podkategorija_id' => null,
                    'kod' => $dijagnoza['kod'],
                    'naziv' => $dijagnoza['naziv'],
                    'naziv_lat' => $dijagnoza['naziv_lat'] ?? null,
                    'aktivan' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]
            );
        }

        $this->command->info('MKB-10 dijagnoze uspješno unesene! Ukupno: ' . count($dijagnoze));
    }
}
